# pull official base image
FROM node:18.0.0-alpine3.15

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN npm install

# add app
COPY . .

EXPOSE 3006

# start app
CMD ["npm", "start"]
