version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD = 12345678
      MYSQL_DATABASE = schoolapp
    ports:
      - 3306:3306
  lb4-app:
    depends_on:
      - db
    build: .
    ports:
      - 3000:3000
    environment:
      - DATASOURCE_URL=mysql://root:secret@db:3306/schoolapp
