version: '3.7'

services:
  mysql:
    container_name: mysql-school-app
    image: mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: schoolapp
      MYSQL_PASSWORD: secret
    networks:
      - mysql-school-app
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: lb4-school-app
    image: lb4-school-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - mysql-school-app

networks:
  mysql-school-app:
 